### ISSUE TITLE
想对这个课程的红警选题project详细了解

### ISSUE THREAD

**Issue by Yitong806** [Greilfang/Our-Red-Alert#4]
您好。看了你们小组使用C++制作的红色警戒游戏，感觉非常精彩，很符合我对这个游戏的认知。
我是南方科技大学的大三学生，对该项目选题很感兴趣，请问能否共享一下该项目的说明文档与评分细则？

**Comment by troysung** [comment]
你好，感谢你的关注，项目的说明文档和评分细则见附件，祝您工作和学习顺利。2022年7月5日下午5:53，YeeTone WANG ***@***.***> 写道：您好。看了你们小组使用C++制作的红色警戒游戏，感觉非常精彩，很符合我对这个游戏的认知。 我是南方科技大学的大三学生，对该项目选题很感兴趣，请问能否共享一下该项目的说明文档与评分细则？—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by Yitong806** [comment]
感谢。请问是在repo的README中吗？是否有更详细的附件？

**Comment by troysung** [comment]
请检查你的邮箱或者查看最新的PR - commit hash: 0980e851226c0aa3889947ec93de9b2ae88bb005

**Comment by Yitong806** [comment]
非常感谢！
